#!/command/with-contenv bash

unit_bootstrap_filesystem() {
    if [ ! -d "${UNIT_CONTROL_SOCKET_PATH}" ]; then
        mkdir -p "${UNIT_CONTROL_SOCKET_PATH}"
    fi
    if [ "$(stat -c %U "${UNIT_CONTROL_SOCKET_PATH}")" != "${UNIT_USER}" ] ; then silent chown "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_CONTROL_SOCKET_PATH}" ; fi

    if [ "${UNIT_LOG_TYPE,,}" = "file" ]; then
        if [ ! -d "${UNIT_LOG_PATH}" ]; then
            mkdir -p "${UNIT_LOG_PATH}"
        fi

        if [ "$(stat -c %U "${UNIT_LOG_PATH}")" != "${UNIT_USER}" ] ; then chown "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_LOG_PATH}" ; fi
        touch "${UNIT_LOG_PATH}"/"${UNIT_LOG_FILE}"
        chown -R "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_LOG_PATH}"/"${UNIT_LOG_FILE}"
    fi

    if [ "${UNIT_LOG_ACCESS_TYPE,,}" = "file" ]; then
        if [ "${UNIT_LOG_ACCESS_PATH}" != "${UNIT_LOG_PATH}" ] && [ "${UNIT_LOG_ACCESS_TYPE,,}" != "none" ]; then
            if [ ! -d "${UNIT_LOG_ACCESS_PATH}" ]; then
                mkdir -p "${UNIT_LOG_ACCESS_PATH}"
            fi

            if [ "$(stat -c %U "${UNIT_LOG_ACCESS_PATH}")" != "${UNIT_USER}" ] && [ "${UNIT_LOG_ACCESS_TYPE,,}" != "none" ]; then
                chown "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_LOG_ACCESS_PATH}"
                touch "${UNIT_LOG_ACCESS_PATH}"/"${UNIT_LOG_ACCESS_FILE}"
                chown -R "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_LOG_ACCESSPATH}"/"${UNIT_LOG_ACCESS_FILE}"
            fi
        fi
    fi

    if [ ! -d "${UNIT_MODULE_PATH}" ]; then
        mkdir -p "${UNIT_MODULE_PATH}"
    fi
    if [ "$(stat -c %U "${UNIT_MODULE_PATH}")" != "${UNIT_USER}" ] ; then silent chown "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_MODULE_PATH}" ; fi

    if [ ! -d "${UNIT_STATE_PATH}" ]; then
        mkdir -p "${UNIT_STATE_PATH}"
    fi
    if [ "$(stat -c %U "${UNIT_STATE_PATH}")" != "${UNIT_USER}" ] ; then chown "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_STATE_PATH}" ; fi
}

unit_configure_instance() {
    _unit_configure_log_format() {
        print_debug "Updating access_log/logformat settings"
        case "${UNIT_LOG_TYPE,,}" in
            file)
                create_logrotate unit "${UNIT_LOG_ACCESS_PATH}"/"${UNIT_LOG_ACCESS_FILE}" unit "${UNIT_USER}" "${UNIT_GROUP}"
            ;;
        esac

        case "${UNIT_LOG_ACCESS_TYPE,,}" in
            console)
                yq -iP '.path="/dev/stdout"' /etc/unit/snippets/access_log/${UNIT_LOG_ACCESS_FORMAT,,}.json -o json
            ;;
            file)
                yq -iP '.path="'$(echo "${UNIT_LOG_ACCESS_PATH}"/"${UNIT_LOG_ACCESS_FILE}")'"' /etc/unit/snippets/access_log/${UNIT_LOG_ACCESS_FORMAT,,}.json -o json
                create_logrotate unit-access "${UNIT_LOG_ACCESS_PATH}"/"${UNIT_LOG_ACCESS_FILE}" unit-access-"${UNIT_LOG_ACCESS_FORMAT,,}" "${UNIT_USER}" "${UNIT_GROUP}"
            ;;
            none)
                yq -iP '.path="/dev/null"' /etc/unit/snippets/access_log/${UNIT_LOG_ACCESS_FORMAT,,}.json -o json
            ;;
        esac
    }

    _unit_configure_settings() {
        print_debug "Updating unit.json settings"
        yq -iP  '
                    .http.body_read_timeout = env(UNIT_TIMEOUT_BODY_READ) |
                    .http.header_read_timeout = env(UNIT_TIMEOUT_HEADER_READ) |
                    .http.idle_timeout = env(UNIT_TIMEOUT_IDLE) |
                    .http.send_timeout = env(UNIT_TIMEOUT_BODY_SEND) |
                    .http.max_body_size = env(UNIT_MAX_BODY_SIZE) |
                    .http.discard_unsafe_fields = env(UNIT_DISCARD_UNSAFE_FIELDS) |
                    .http.log_route = env(UNIT_LOG_ROUTES) |
                    .http.server_version = env(UNIT_ENABLE_SERVER_VERSION)
                ' /etc/unit/snippets/unit.json -o json
    }

    _unit_configure_log_format
    _unit_configure_settings
}

unit_configure_monitoring() {
    if var_true "${CONTAINER_ENABLE_MONITORING}" && [ "${CONTAINER_MONITORING_BACKEND,,}" = "zabbix" ]; then
        source /assets/defaults/03-monitoring

        case "${UNIT_CONTROL_TYPE,,}" in
        ip)
            _monitor_control="http://${_unit_control}/status"
        ;;
        socket)
            _monitor_control="--unix-socket $(echo "${_unit_control}" | sed "s|unix:/||g") http://tiredofit/status"
        ;;
        esac

        cat <<EOF > "${ZABBIX_CONFIG_PATH}"/"${ZABBIX_CONFIG_FILE}.d"/tiredofit_unit.conf
# Zabbix Unit Configuration - Automatically Generated
# Find Companion Zabbix Server Templates at https://github.com/tiredofit/docker-unit
# Autoregister=unit

UserParameter=unit.get_statistics,curl -s -X GET ${_monitor_control}
UserParameter=unit.version,unitd --version 2>/tmp/.unit.version ; head -n1 /tmp/.unit.version | awk '{print \$3}'
EOF

        chmod 700 "${ZABBIX_CONFIG_PATH}"/"${ZABBIX_CONFIG_FILE}.d"/tiredofit_unit.conf
        chown zabbix:root "${ZABBIX_CONFIG_PATH}"/"${ZABBIX_CONFIG_FILE}.d"/tiredofit_unit.conf
    fi
}

unit_configure_site() {
    _unit_configure_application() {
        if [ "${UNIT_APPLICATION_PROCESS_TYPE,, }" = "dynamic" ] ; then
            yq -iP '
                        .*.processes.max=env(UNIT_APPLICATION_PROCESS_MAX) |
                        .*.processes.spare=env(UNIT_APPLICATION_PROCESS_SPARE) |
                        .*.processes.idle_timeout=env(UNIT_APPLICATION_PROCESS_TIMEOUT)
                    ' -o json "${1}".json
        fi

        if [[ "${UNIT_APPLICATION_LIMIT_REQUEST_RECYCLE}" -ge 1 ]] ; then
            yq -iP '
                        .*.limits.requests=env(UNIT_APPLICATION_LIMIT_REQUEST_RECYCLE)
                    ' -o json "${1}".json
        fi

        if [[ "${UNIT_APPLICATION_LIMIT_TIMEOUT}" -ge 1 ]] ; then
            yq -iP '
                        .*.limits.timeout=env(UNIT_APPLICATION_LIMIT_TIMEOUT)
                    ' -o json "${1}".json
        fi
    }

    _unit_configure_listener() {
        if var_true "${UNIT_ENABLE_XFORWARDED_PROTOCOL}" ; then
            xforward_proto_array=$(echo "${UNIT_XFORWARDED_PROTOCOL_IP}" | tr "," "\n")

            for ip in $xforward_proto_array; do
                export xforward_proto_prepared="${xforward_proto_prepared},\"${ip}\""
            done

            yq -iP  '
                        .*.forwarded.protocol="X-Forwarded-Proto" |
                        .*.forwarded.source=['$(echo "${xforward_proto_prepared}" | sed "s|^,||g")']
                    ' -o json "${1}".json
        fi
    }

    _unit_configure_site_default() {
        if [ -z "${UNIT_SITE_ENABLED}" ] && [ ! -f "/etc/unit/sites.available/default-listener.json" ] && [ ! -f "/etc/cont-init.d/20-unit-php" ] ; then
            UNIT_SITE_ENABLED=default
            yq -nP  '
                        ."'$(echo "${UNIT_LISTEN_IP}:${UNIT_LISTEN_PORT}")'".pass="routes"
                    ' -o json > /etc/unit/sites.available/"${UNIT_SITE_ENABLED}"-listener.json

            cat <<EOF > /etc/unit/sites.available/"${UNIT_SITE_ENABLED}"-route.json
   [
      {
         "action":{
            "share": "${UNIT_WEBROOT}/\$uri"
         }
      }
   ]
EOF

            # Not entirely working yet - Does it need to? Probably just for cool factor.
            #yq -nP  '
            #            .listeners."'$(echo "${UNIT_LISTEN_IP}:${UNIT_LISTEN_PORT}")'".pass="routes" |
            #            .routes.action.share = "'$(echo "${UNIT_WEBROOT}")'/$uri"
            #        ' -o json > /etc/unit/sites.available/default.json
            _unit_configure_listener /etc/unit/sites.available/default-listener
        fi
    }

    _unit_configure_site_targetted() {
        update_template /etc/unit/sites.available/${1}-listener.json \
                                                            UNIT_LISTEN_IP \
                                                            UNIT_LISTEN_PORT \
                                                            UNIT_SITE_ENABLED

        update_template /etc/unit/sites.available/${1}-upstream.json \
                                                            UNIT_UPSTREAM_HOST \
                                                            UNIT_SITE_ENABLED

        update_template /etc/unit/sites.available/${1}-route.json \
                                                            UNIT_SITE_ENABLED \
                                                            UNIT_WEBROOT

        update_template /etc/unit/sites.available/${1}-application.json \
                                                            UNIT_SITE_ENABLED \
                                                            UNIT_WEBROOT
    }

    if [ -n "${1}" ]; then
        case "${1}" in
            default)
                _unit_configure_site_default
            ;;
            all)
                for config in /etc/unit/sites.available/*.json ; do
                    _unit_configure_site_targetted $(basename $config)
                done

                for application in /etc/unit/sites.available/*-application.json ; do
                    _unit_configure_application "${application}"
                done

                for listener in /etc/unit/sites.available/*-listener.json ; do
                    _unit_configure_listener "${listener}"
                done
            ;;
            *)
                if compgen -G "/etc/unit/sites.available/${1}*.json" >/dev/null ; then
                    _unit_configure_site_targetted "${1}"
                fi

                if compgen -G "/etc/unit/sites.available/${1}-application.json" >/dev/null ; then
                    _unit_configure_application /etc/unit/sites.available/"${1}"-application.json
                fi

                if compgen -G "/etc/unit/sites.available/${1}-listener.json" >/dev/null ; then
                    _unit_configure_listener /etc/unit/sites.available/"${1}"-listener.json
                fi
            ;;
        esac
    else
        if [ -n "${UNIT_SITE_ENABLED}" ]; then
            _unit_configure_site_targetted "${UNIT_SITE_ENABLED}"
            if compgen -G "/etc/unit/sites.available/${UNIT_SITE_ENABLED}-application.json" >/dev/null ; then
                _unit_configure_application /etc/unit/sites.available/"${UNIT_SITE_ENABLED}"-application.json
            fi
            if compgen -G "/etc/unit/sites.available/${UNIT_SITE_ENABLED}-listener.json" >/dev/null ; then
                _unit_configure_listener /etc/unit/sites.available/"${UNIT_SITE_ENABLED}"-listener.json
            fi

        else
            _unit_configure_site_default
        fi
    fi
}

unit_create_sample_html() {
    if [ ! -f "${UNIT_WEBROOT}/index.html" ]; then
        print_notice "Creating sample index.html"
        mkdir -p "${UNIT_WEBROOT}"
        cat <<EOF >"${UNIT_WEBROOT}"/index.html
<html>
<title>Default Page</title>
<h2>Container is working</h2>
Congratulations! Your ${IMAGE_NAME} image is working. You are seeing this because you don't have an index.html file in your ${UNIT_WEBROOT} directory.
</html>
EOF
        chown -R "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_WEBROOT}"
    fi
}

unit_post_init() {
    if var_true "${UNIT_ENABLE_APPLICATION_CONFIGURATION}" ; then
        if [ -n "${UNIT_SITE_ENABLED}" ] ; then
            if [ "${UNIT_SITE_ENABLED,,}" != "null" ] ; then
                sites=$(echo "${UNIT_SITE_ENABLED}" | tr "," "\n")
                for site in $sites; do
                    unit_site_enable "${site}"
                done
            fi
        fi
    fi

    if [ -n "${UNIT_POST_INIT_SCRIPT}" ] ; then
        print_debug "Found Unit Post Init Scripts"
        post_scripts=$(echo "${UNIT_POST_INIT_SCRIPT}" | tr "," "\n")
        for post_script in $post_scripts; do
            if [ -f "${post_script}" ] ; then
                print_debug "Executing post init script '${post_script}'"
                chmod +x "${post_script}"
                "${post_script}"
            else
                print_error "Tried to run post script '${post_script}' but it does not exist!"
            fi
        done
    fi

    if [ -n "${UNIT_POST_INIT_COMMAND}" ] ; then
        print_debug "Found Post Init Command"
        post_commands=$(echo "${UNIT_POST_INIT_COMMAND}" | tr "," "\n")
        for post_command in $post_commands ; do
            print_debug "Executing post init command '${post_command}'"
            "${post_command}"
    	done
    fi

    mkdir -p "${UNIT_WEBROOT}"
    if var_true "${UNIT_FORCE_RESET_PERMISSIONS}" ; then
        chown -R "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_WEBROOT}"
    fi
}

unit_site_disable() {
    if [ -n "${1}" ]; then
        if [ "${1,,}" = "all" ] ; then
            for site in /etc/unit/sites.enabled/*.json; do
                print_debug "Disabling Unit Site '$(basename "${site}")"
                rm -rf /etc/unit/sites.enabled/"$(basename "${site}")"
            done
        else
            if compgen -G "/etc/unit/sites.available/${1}*.json" >/dev/null ; then
                print_debug "Disabling Unit Site '${1}'"
                rm -rf /etc/unit/sites.enabled/"${1}"*.json
            else
                print_error "Cannot disable site ${1} as it doesn't exist in /etc/unit/sites.enabled!"
                exit 1
            fi
        fi
    else
        print_error "Need configuration file as argument to utilize 'unit_site_disable' function"
    fi
}

unit_site_enable() {
    if [ -n "${1}" ]; then
        if [ "${1,,}" = "all" ] ; then
            if [ "$(ls -A /etc/unit/sites.available/)" ]; then
                for site in /etc/unit/sites.available/*.json; do
                    print_debug "Enabling Unit Site '$(basename "${site}")'"
                    ln -sf /etc/unit/sites.available/"$(basename "${site}")" /etc/unit/sites.enabled/
                done
            fi
        else
            if compgen -G "/etc/unit/sites.available/${1}*.json" >/dev/null ; then
                print_debug "Enabling Unit Site '${1}'"
                for site in /etc/unit/sites.available/"${1}"*.json; do
                    ln -sf "${site}" /etc/unit/sites.enabled
                done
            else
                print_error "Cannot enable site ${1} as it doesn't exist in /etc/unit/sites.available!"
                exit 1
            fi
        fi
    else
        print_error "Need json configuration file as argument to utilize 'unit_site_enable' function"
    fi
}
