#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="unit"
prepare_service defaults single

check_container_initialized
check_service_initialized init

liftoff

print_start "Starting unit ${UNIT_VERSION}"
silent exec unitd \
                --control "${_unit_control}" \
                --user "${UNIT_USER}" \
                --group "${UNIT_GROUP}" \
                --no-daemon ${_unit_log} \
                --tmp "${UNIT_TMP_PATH}" $${UNIT_OPTS}
