#!/command/with-contenv bash

CONFIG_PATH=${CONFIG_PATH:-"/config/"}
DATA_PATH=${DATA_PATH:-"/data/"}
LOG_FILE=${LOG_FILE:-"log.log"}
LOG_TYPE=${LOG_TYPE:-"FILE"}
LOG_PATH=${LOG_PATH:-"/logs/"}
SETUP_MODE=${SETUP_MODE:-"AUTO"}
